import urllib.request

from bs4 import BeautifulSoup

from text_enrichment.text_enrichment import TextEnricher


class ArticleParser():
    def __init__(self):
        self.parsers = all_parsers()

    def parse_article(self, article_metadata):
        with urllib.request.urlopen(article_metadata['url']) as response:
            article_html = response.read()
        article_soup = BeautifulSoup(article_html, 'lxml')
        return self.parsers[article_metadata['source']](article_metadata, article_soup)

    def add_parser(self, source, parser):
        self.parsers[source] = parser


# TODO move these functions to another file
def reuters_parser(article_metadata, article_soup):
    return {
        **article_metadata,
        'fullText': ''.join([p.get_text() for p in article_soup.select('#article-text > p')])
    }


def cnn_parser(article_metadata, article_soup):
    paragraphs = article_soup.select('.zn-body__paragraph')
    # Remove <cite class="el-editorial-source"> (CNN)</cite> from first paragraph
    if len(paragraphs) > 0:
        citation = paragraphs[0].select(".el-editorial-source")
        if len(citation) > 0:
            citation[0].extract()
    return {
        **article_metadata,
        'fullText': ''.join([p.get_text() for p in paragraphs])
    }


def all_parsers():
    return {
        "reuters": reuters_parser,
        "cnn": cnn_parser
    }


if __name__ == '__main__':
    articles = [{
        'author': 'Lesley Wroughton and Yeganeh Torbati',
        'source': 'reuters',
        'title': 'U.S. air strike gives Tillerson a boost for Moscow talks',
        'description': "U.S. Secretary of State Rex Tillerson's visit to Moscow this week will be an early test of whether the Trump administration can use any momentum generated by striking a Syrian air base to craft and execute a strategy to end the Syrian war.",
        'url': 'http://www.reuters.com/article/us-usa-russia-tillerson-idUSKBN17C0D4',
        'urlToImage': 'http://s3.reutersmedia.net/resources/r/?m=02&d=20170410&t=2&i=1180051153&w=&fh=545px&fw=&ll=&pl=&sq=&r=LYNXMPED39077',
        'publishedAt': '2017-04-10T08:08:52Z'
    },
        {
            "author": "Ben Westcott, CNN",
            "source": "cnn",
            "title": "US warns Russia over support for Assad",
            "description": "Foreign ministers of leading industrialized nations were meeting Monday amid heightened tensions between Russia and the United States over the Trump administration's unexpected military strike on a Syrian airbase.",
            "url": "http://www.cnn.com/2017/04/10/politics/syria-russia-iran-missile-strikes/index.html",
            "urlToImage": "http://i2.cdn.cnn.com/cnnnext/dam/assets/170328141858-russia-jet-syria-tease-super-tease.jpg",
            "publishedAt": "2017-04-10T09:59:38Z"
        }]

    ap = ArticleParser()
    ap.add_parser('reuters', reuters_parser)
    ap.add_parser('cnn', cnn_parser)

    te = TextEnricher()

    for article in articles[-1:]:
        parsed = ap.parse_article(article)
        annotated = te.enrichDocument(parsed)
        print(annotated)
