from bs4 import BeautifulSoup
import urllib.request

class ArticleParser():
    def __init__(self):
        self.parsers = {}

    def parse_article(self, article_metadata):
        with urllib.request.urlopen(article_metadata['url']) as response:
            article_html = response.read()
        article_soup = BeautifulSoup(article_html, 'lxml')
        return self.parsers[article_metadata['source']](article_metadata, article_soup)

    def add_parser(self, source, parser):
        self.parsers[source] = parser


# TODO move these functions to another file
def reuters_parser(article_metadata, article_soup):
    return {
        **article_metadata,
        'fullText': ''.join([p.get_text() for p in article_soup.select('#article-text > p')])
    }


if __name__ == '__main__':
    article_metadata = {
        'author': 'Lesley Wroughton and Yeganeh Torbati',
        'source': 'reuters',
        'title': 'U.S. air strike gives Tillerson a boost for Moscow talks',
        'description': "U.S. Secretary of State Rex Tillerson's visit to Moscow this week will be an early test of whether the Trump administration can use any momentum generated by striking a Syrian air base to craft and execute a strategy to end the Syrian war.",
        'url': 'http://www.reuters.com/article/us-usa-russia-tillerson-idUSKBN17C0D4',
        'urlToImage': 'http://s3.reutersmedia.net/resources/r/?m=02&d=20170410&t=2&i=1180051153&w=&fh=545px&fw=&ll=&pl=&sq=&r=LYNXMPED39077',
        'publishedAt': '2017-04-10T08:08:52Z'
    }

    ap = ArticleParser()
    ap.add_parser('reuters', reuters_parser)

    print(ap.parse_article(article_metadata)['fullText'])
